[package]
name = "sheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12"
tokio = { version="1.5", features=["rt", "rt-multi-thread", "time", "macros"]}
async-trait = "0.1"