[package]
name = "timer-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.12"
chrono = "0.4"
lazy_static = "1"
timer-utils = { path = "../timer-utils" }